version: '3.7'

networks:
  web_declaraciones:
    ipam:
      config:
        - subnet: 192.168.156.0/24
volumes:
  datavolume:

services:
  db:
    image: mariadb:10.6.4
    container_name: declaraciones_db
    restart: always
    ports:
      - 3306
    env_file:
      - .env
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_ROOT_USER=${MYSQL_ROOT_USER}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}

    volumes:
      - ./db/scripts/declaraciones_mysql.cnf:/etc/mysql/conf.d/docker.cnf
      - ./db/declaraciones/data:/var/lib/mysql
    networks:
      web_declaraciones:
        ipv4_address: 192.168.156.2
  

  nginx:
    image: nginx:alpine
    volumes:
      - ./serv_proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./serv_proxy/conf:/etc/nginx/conf.d
      - ./declaraciones/staticfiles:/django_static
      - ./declaraciones/media:/django_media
    ports:
      - "80:80"
    restart: always
    depends_on:
      - declaraciones
    networks:
      web_declaraciones:
        ipv4_address: 192.168.156.4

  redis:
    container_name: declaraciones_cache
    image: redis:alpine
    ports:
      - 6379
    restart: always
    networks:
      web_declaraciones:
        ipv4_address: 192.168.156.3

  declaraciones:
    container_name: declaraciones_django
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: >
      bash -c "echo .......... &&
            sleep 20s &&
            sh -c "/wait" &&
            pip install --upgrade pip &&
            pip install -r requirements.txt &&
            echo .... python3 clearredis.py &&
            sh loaddata.sh &&
            cp settings.py /usr/local/lib/python3.8/site-packages/oauth2_provider/
            cp oauth2_validators.py /usr/local/lib/python3.8/site-packages/oauth2_provider/
            cp urls.py /usr/local/lib/python3.8/site-packages/oauth2_provider/
            echo ...................................... loaddata &&
            apt-get update&&
            apt-get install --yes --force-yes uwsgi-plugin-python3&&
            uwsgi --ini  uwsgi.ini"
    working_dir: /code/declaraciones
    restart: always
    volumes:
      - .:/code
    expose:
      - "8000"
    networks:
      web_declaraciones:
        ipv4_address: 192.168.156.5

  phpmyadmin:
    depends_on:
      - declaraciones
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: declaraciones_db
      PMA_ARBITRARY: 1
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    networks:
      web_declaraciones:
        ipv4_address: 192.168.156.7

